all: main

main:
	@gcc main.c -o main


#w celu przetestowania najlepiej zmienic na wlasna wybrana sciezke
test:
	@gcc main.c -o main
	@./main /Users/jakubzywiecki/Downloads/ "#include"

clean:
	@rm main